Feature/grids
trailbehind/leaflet-grids pull request #2
Opened 2016-11-29 02:23 UTC by alex-outdoor

Made a PR to make feedback easier but work not done. 
If I could have your comments on 2 issues I am facing : 

1) Some labels at some zoom level doesn't appeared to be centered inside the UTM zone. At some zoom level, it even appears twice and sometimes it's broken. 

2) At zoom level 11 for example, it takes longer to display the labels as it's looping a lot. Would there be a better way to optimize the computation ?

2016-11-29 14:54 UTC, JesseCrocker commented
The only thing i noticed that seemed wrong from a quick look at the code is that the loop that adds the labels, line 842, is inside the loop thats started on line 769, Maybe thats causing the duplicated labels?

2016-12-03 00:13 UTC, alex-outdoor commented
![duplicatelabels](https://cloud.githubusercontent.com/assets/18466177/20854530/a32ee77e-b8a9-11e6-96b4-507da78c71ac.jpg)
I have this issue where even if I check before drawing if the labelPt coordinate is inside the map screen - It still draws way too many points. Like on the pictures, it's supposed to show 12 waypoints but instead 156 points are drawn (and not all of them are visible which is weird).
I did try to console.log almost everything I could to do the math but didn't find what causes it.

2016-12-08 20:23 UTC, alex-outdoor commented
I think this is ready to get reviewed. 
Next step : 
1) Integrate it to gaiacloud /map
2) Integrate it to the map print

2016-12-08 20:41 UTC, JesseCrocker commented
@alex-outdoor I changed the base on this master, because the whole thing needs to be reviewed, not just your changes

2016-12-08 20:42 UTC, JesseCrocker commented
There's a file that looks like it doesnt belong DuplicateLabels.jpg

2016-12-09 13:59 UTC, JesseCrocker commented
It looks like maybe a rounding issue with the labels for the dms grid at zoom 15. the labels say 59" and 29" instead of 0" and 30"
![screen shot 2016-12-09 at 6 57 09 am](https://cloud.githubusercontent.com/assets/2048291/21051283/d25d9af8-bddc-11e6-874d-9c763b13da5f.png)

2016-12-09 14:02 UTC, JesseCrocker commented
I think the Grid spacing for MGRS might need to be shifted by 1 level, at zooms 14 and 17 I only get one or 2 squares on screen.

2016-12-09 14:20 UTC, JesseCrocker requested changes
Code looks good, and it works great. Just need a couple minor changes.

2016-12-09 14:20 UTC, JesseCrocker commented on leaflet-grids.js
> +        if(zoom <3){
Unless there is a good reason for this, i think at least the lat/lon grids should work down to zoom 0.

2016-12-09 14:20 UTC, JesseCrocker commented on leaflet-grids.js
> +        console.log(this.gridLabel);
remove log

2016-12-09 14:20 UTC, JesseCrocker commented on leaflet-grids.js
> +    _cleanHorz: function (line, leftLng, rightLng) {
Can you add a comment on what these _clean functions do?

2016-12-09 14:22 UTC, JesseCrocker commented
This closes #1

2016-12-23 00:48 UTC, merged